-- FlowerDoro API initial schema and flower book seed.
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS users (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    device_id varchar(128) NOT NULL UNIQUE,
    display_name varchar(120) NOT NULL DEFAULT '',
    locale varchar(12) NOT NULL DEFAULT 'vi',
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS user_settings (
    user_id uuid PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    work_minutes integer NOT NULL DEFAULT 30 CHECK (work_minutes > 0),
    break_minutes integer NOT NULL DEFAULT 5 CHECK (break_minutes > 0),
    clock_style varchar(40) NOT NULL DEFAULT 'gardenBed',
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS gardens (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
    user_name varchar(120) NOT NULL DEFAULT 'You',
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS flowers (
    id bigserial PRIMARY KEY,
    kind varchar(80) NOT NULL UNIQUE,
    sort_order integer NOT NULL UNIQUE,
    english_name varchar(120) NOT NULL,
    vietnamese_name varchar(120) NOT NULL,
    english_description text NOT NULL DEFAULT '',
    vietnamese_description text NOT NULL DEFAULT '',
    english_fact_1 text NOT NULL DEFAULT '',
    english_fact_2 text NOT NULL DEFAULT '',
    english_fact_3 text NOT NULL DEFAULT '',
    vietnamese_fact_1 text NOT NULL DEFAULT '',
    vietnamese_fact_2 text NOT NULL DEFAULT '',
    vietnamese_fact_3 text NOT NULL DEFAULT '',
    rarity varchar(40) NOT NULL DEFAULT 'common',
    asset_name varchar(120) NOT NULL DEFAULT '',
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS focus_sessions (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    started_at timestamptz NOT NULL,
    completed_at timestamptz,
    focus_minutes integer NOT NULL CHECK (focus_minutes > 0),
    rewarded boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS garden_flowers (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    garden_id uuid REFERENCES gardens(id) ON DELETE CASCADE,
    user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    flower_kind varchar(80) NOT NULL REFERENCES flowers(kind) ON UPDATE CASCADE,
    focus_session_id uuid REFERENCES focus_sessions(id) ON DELETE SET NULL,
    focus_minutes integer NOT NULL CHECK (focus_minutes >= 30),
    earned_at timestamptz NOT NULL DEFAULT now(),
    created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE flowers ADD COLUMN IF NOT EXISTS sort_order integer;
ALTER TABLE flowers ADD COLUMN IF NOT EXISTS english_fact_1 text NOT NULL DEFAULT '';
ALTER TABLE flowers ADD COLUMN IF NOT EXISTS english_fact_2 text NOT NULL DEFAULT '';
ALTER TABLE flowers ADD COLUMN IF NOT EXISTS english_fact_3 text NOT NULL DEFAULT '';
ALTER TABLE flowers ADD COLUMN IF NOT EXISTS vietnamese_fact_1 text NOT NULL DEFAULT '';
ALTER TABLE flowers ADD COLUMN IF NOT EXISTS vietnamese_fact_2 text NOT NULL DEFAULT '';
ALTER TABLE flowers ADD COLUMN IF NOT EXISTS vietnamese_fact_3 text NOT NULL DEFAULT '';
ALTER TABLE garden_flowers ADD COLUMN IF NOT EXISTS garden_id uuid;

CREATE INDEX IF NOT EXISTS idx_garden_flowers_user_earned ON garden_flowers(user_id, earned_at DESC);
CREATE INDEX IF NOT EXISTS idx_garden_flowers_garden_earned ON garden_flowers(garden_id, earned_at DESC);
CREATE INDEX IF NOT EXISTS idx_garden_flowers_kind ON garden_flowers(flower_kind);
CREATE INDEX IF NOT EXISTS idx_focus_sessions_user_started ON focus_sessions(user_id, started_at DESC);

INSERT INTO flowers (kind, sort_order, english_name, vietnamese_name, english_description, vietnamese_description, english_fact_1, english_fact_2, english_fact_3, vietnamese_fact_1, vietnamese_fact_2, vietnamese_fact_3, rarity, asset_name) VALUES
    ('daisy', 1, 'Daisy', 'Cúc họa mi', 'A bright field flower often linked with fresh starts and simple joy.', 'Cúc họa mi có cánh trắng giản dị ôm quanh nhụy vàng tươi.', 'A flower associated with simple white petals and a sunny center.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Thường gợi cảm giác trong trẻo, đồng cỏ và những khởi đầu nhẹ nhàng.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'daisy'),
    ('rose', 2, 'Rose', 'Hoa hồng', 'A classic garden bloom known for layered petals, fragrance, and symbolism.', 'Hoa hồng nổi bật với nhiều lớp cánh mềm và hương thơm cổ điển.', 'A flower cultivated for centuries in many colors and fragrances.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Được trồng từ rất lâu đời, mỗi màu hoa hồng thường mang một ý nghĩa riêng.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'rose'),
    ('sunflower', 3, 'Sunflower', 'Hướng dương', 'A tall, sunny bloom famous for turning its face toward the light.', 'Hướng dương có bông lớn màu vàng và dáng vươn cao về phía nắng.', 'A flower head made from many tiny flowers packed together.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Một đầu hoa hướng dương thật ra gồm rất nhiều hoa nhỏ xếp sát nhau.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'sunflower'),
    ('tulip', 4, 'Tulip', 'Tulip', 'A spring bulb flower with smooth cup-shaped petals and bold colors.', 'Tulip là hoa củ mùa xuân với dáng cúp mượt và màu sắc rõ nét.', 'A bulb flower strongly associated with spring gardens.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Những luống tulip thường báo hiệu mùa xuân ở các khu vườn ôn đới.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'tulip'),
    ('lotus', 5, 'Lotus', 'Hoa sen', 'A water flower that rises from muddy ponds and opens clean above the surface.', 'Hoa sen mọc từ bùn nước nhưng nở thanh sạch trên mặt ao.', 'An aquatic bloom with leaves that naturally repel water.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Lá sen có bề mặt đẩy nước, làm giọt nước lăn đi rất dễ dàng.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'lotus'),
    ('lavender', 6, 'Lavender', 'Oải hương', 'A fragrant purple herb-flower often used for calm scents and small bouquets.', 'Oải hương có chùm hoa tím thơm, thường gắn với cảm giác thư thái.', 'A flower spike loved for its calming scent.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Các cành hoa nhỏ được phơi khô để giữ hương trong túi thơm và bó hoa.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'lavender'),
    ('orchid', 7, 'Orchid', 'Hoa lan', 'An elegant flower family with sculptural petals and many rare-looking shapes.', 'Hoa lan có dáng cánh tinh tế và rất nhiều hình dạng lạ mắt.', 'One of the largest and most varied flowering plant families.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Lan là một trong những họ thực vật có hoa đa dạng nhất thế giới.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'orchid'),
    ('cherryBlossom', 8, 'Cherry Blossom', 'Hoa anh đào', 'A delicate spring blossom admired for soft pink petals and a short bloom season.', 'Hoa anh đào nở thành mây hồng nhạt trong một mùa rất ngắn.', 'A spring blossom celebrated for its brief, poetic bloom.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Vẻ đẹp ngắn ngủi của hoa thường gợi cảm giác mong manh và thơ mộng.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'cherry-blossom'),
    ('poppy', 9, 'Poppy', 'Hoa anh túc', 'A vivid, papery flower with a dark center and a strong wildflower silhouette.', 'Hoa anh túc có cánh mỏng như giấy và nhụy đậm nổi bật.', 'A flower known for thin petals and open sunny habitats.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Dáng hoa mở rộng rất hợp với những bãi hoa nắng và cảnh đồng nội.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'poppy'),
    ('hydrangea', 10, 'Hydrangea', 'Cẩm tú cầu', 'A round cluster flower whose color can shift with soil conditions.', 'Cẩm tú cầu nở thành cụm tròn lớn với nhiều bông nhỏ chen nhau.', 'A clustered bloom that can change color with soil acidity.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Màu hoa có thể đổi theo độ chua của đất ở một số giống.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'hydrangea'),
    ('peony', 11, 'Peony', 'Mẫu đơn', 'A lush perennial bloom with many soft petals and a romantic garden presence.', 'Mẫu đơn có nhiều lớp cánh mềm, tạo vẻ đầy đặn và sang trọng.', 'A long-lived perennial often prized for full, layered blooms.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Cây lâu năm này thường được yêu thích vì bông lớn và mùa nở rực rỡ.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'peony'),
    ('camellia', 12, 'Camellia', 'Hoa trà', 'A glossy-leaved shrub flower with precise petals and a refined look.', 'Hoa trà có lá bóng xanh đậm và cánh xếp gọn như được chăm chút.', 'An evergreen shrub bloom that often flowers in cooler seasons.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Nhiều giống hoa trà nở vào mùa mát, khi vườn còn ít màu sắc.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'camellia'),
    ('gardenia', 13, 'Gardenia', 'Dành dành', 'A creamy white flower famous for a rich, sweet fragrance.', 'Dành dành có hoa trắng kem và hương thơm ngọt, dày, rất dễ nhớ.', 'A fragrant bloom often grown for perfume-like scent.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Hương dành dành thường được ví như mùi nước hoa tự nhiên trong vườn.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'gardenia'),
    ('jasmine', 14, 'Jasmine', 'Hoa nhài', 'A small starry flower known for sweet evening fragrance.', 'Hoa nhài nhỏ hình sao, tỏa hương ngọt nhất là vào chiều tối.', 'A fragrant flower used in teas, perfumes, and garden arches.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Hoa nhài xuất hiện trong trà, nước hoa và các giàn leo thơm.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'jasmine'),
    ('magnolia', 15, 'Magnolia', 'Mộc lan', 'A large elegant blossom that appears on trees and shrubs.', 'Mộc lan có bông lớn, dáng thanh lịch trên cây gỗ hoặc cây bụi.', 'An ancient flowering lineage with bold, sculptural blooms.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Đây là nhóm hoa cổ xưa với cánh dày và dáng nở rất điêu khắc.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'magnolia'),
    ('hibiscus', 16, 'Hibiscus', 'Dâm bụt', 'A tropical-looking flower with broad petals and a showy center.', 'Dâm bụt mang vẻ nhiệt đới với cánh lớn và phần nhụy vươn dài.', 'A warm-climate bloom often associated with vivid colors.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Hoa thường có màu rực rỡ, hợp với khí hậu ấm và nhiều nắng.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'hibiscus'),
    ('marigold', 17, 'Marigold', 'Cúc vạn thọ', 'A cheerful gold or orange flower often used in borders.', 'Cúc vạn thọ có sắc vàng cam ấm, làm viền vườn rất nổi bật.', 'A hardy garden bloom valued for long-lasting color.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Hoa bền màu và dễ trồng nên thường xuất hiện trong nhiều khu vườn.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'marigold'),
    ('chrysanthemum', 18, 'Chrysanthemum', 'Cúc đại đóa', 'A many-petaled flower strongly tied to autumn gardens.', 'Cúc đại đóa có nhiều lớp cánh và thường gắn với sắc thu.', 'An autumn bloom with many forms, from pompons to daisies.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Họ cúc có rất nhiều dạng, từ cánh đơn đến bông tròn dày như pompon.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'chrysanthemum'),
    ('dahlia', 19, 'Dahlia', 'Thược dược', 'A bold tuber-grown flower with dramatic geometric petals.', 'Thược dược có bông lớn, cánh xếp hình học và màu sắc mạnh mẽ.', 'A tuber flower famous for an enormous range of shapes.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Cây mọc từ củ và có vô số kiểu cánh, kích thước, màu hoa.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'dahlia'),
    ('zinnia', 20, 'Zinnia', 'Cúc zinnia', 'A bright annual flower that brings strong summer color.', 'Cúc zinnia là hoa mùa hè rực rỡ, dáng khỏe và màu rất tươi.', 'An easy annual often grown for cutting gardens.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Loài hoa hằng năm này thường được trồng để cắt cành và làm sáng luống hoa.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'zinnia'),
    ('carnation', 21, 'Carnation', 'Cẩm chướng', 'A ruffled flower known for spicy fragrance and long vase life.', 'Cẩm chướng có cánh viền răng cưa, hương cay nhẹ và giữ hoa lâu.', 'A cut flower with fringed petals and many color meanings.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Trong bó hoa, cẩm chướng được yêu thích vì bền và có nhiều màu biểu cảm.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'carnation'),
    ('daffodil', 22, 'Daffodil', 'Thủy tiên vàng', 'A spring bulb with a trumpet center and bright yellow charm.', 'Thủy tiên vàng có tâm kèn nổi bật và sắc vàng báo mùa xuân.', 'A bulb flower often considered a sign of spring.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Đây là hoa củ thường nở sớm, làm khu vườn sáng lên sau mùa lạnh.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'daffodil'),
    ('iris', 23, 'Iris', 'Diên vĩ', 'A graceful flower with folded petals and sword-like leaves.', 'Diên vĩ có cánh uốn mềm, lá như lưỡi kiếm và dáng rất duyên.', 'A bloom named after the rainbow in Greek tradition.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Tên iris gắn với cầu vồng, hợp với bảng màu phong phú của loài hoa này.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'iris'),
    ('bluebell', 24, 'Bluebell', 'Chuông xanh', 'A nodding woodland flower that can carpet shady ground.', 'Chuông xanh có hoa rủ hình chuông, thường phủ kín nền rừng mát.', 'A bell-shaped flower often seen in cool woodland scenes.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Những thảm chuông xanh tạo cảm giác cổ tích ở các khu rừng mùa xuân.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'bluebell'),
    ('foxglove', 25, 'Foxglove', 'Mao địa hoàng', 'A tall spike of tubular bells loved in cottage gardens.', 'Mao địa hoàng mọc thành tháp hoa chuông dài, rất nổi trong vườn cottage.', 'A vertical flower spike that attracts pollinators.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Các ống hoa cao thu hút nhiều loài thụ phấn ghé thăm.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'foxglove'),
    ('snapdragon', 26, 'Snapdragon', 'Hoa mõm sói', 'A playful flower spike with blooms that resemble tiny mouths.', 'Hoa mõm sói có bông xếp dọc thân, từng hoa giống chiếc miệng nhỏ.', 'A cool-season flower known for stacked, dragon-like blossoms.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Khi bóp nhẹ, hoa có thể mở khép như mõm rồng nên rất vui mắt.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'snapdragon'),
    ('anemone', 27, 'Anemone', 'Hoa hải quỳ', 'A delicate bloom with a dark center and windflower charm.', 'Hoa hải quỳ có cánh mảnh, tâm đậm và vẻ nhẹ như gió.', 'A flower often called windflower in garden traditions.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Trong nhiều truyền thống làm vườn, anemone còn được gọi là hoa gió.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'anemone'),
    ('ranunculus', 28, 'Ranunculus', 'Mao lương', 'A rose-like bloom made from many thin, silky petals.', 'Mao lương có cánh mỏng xếp dày, nhìn như một đóa hồng bằng lụa.', 'A cut flower prized for dense, layered petals.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Hoa cắt cành này được chuộng vì lớp cánh nhiều và màu trong trẻo.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'ranunculus'),
    ('freesia', 29, 'Freesia', 'Lan Nam Phi', 'A fragrant flower spike with graceful funnel-shaped blooms.', 'Lan Nam Phi có chùm hoa phễu cong mềm và hương thơm rõ.', 'A scent-rich bloom often used in bouquets.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Những cành freesia thường xuất hiện trong bó hoa nhờ mùi hương tươi.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'freesia'),
    ('geranium', 30, 'Geranium', 'Phong lữ', 'A familiar garden flower grown for clusters of bright blooms.', 'Phong lữ có cụm hoa tròn sáng màu và lá bo tròn dễ nhận ra.', 'A container favorite with rounded leaves and clustered flowers.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Cây rất hợp trồng chậu, ban công và bồn cửa sổ.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'geranium'),
    ('begonia', 31, 'Begonia', 'Thu hải đường', 'A shade-friendly flower with soft petals and decorative leaves.', 'Thu hải đường chịu bóng tốt, vừa có hoa mềm vừa có lá trang trí.', 'A garden plant valued for both blooms and foliage.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Nhiều giống begonia được yêu thích cả vì màu lá lẫn dáng hoa.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'begonia'),
    ('azalea', 32, 'Azalea', 'Đỗ quyên', 'A shrub flower that can cover branches in vivid spring color.', 'Đỗ quyên phủ cành bằng những bông hoa xuân rực rỡ.', 'A woodland shrub bloom often grown in acidic soil.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Cây bụi này thường thích đất chua và không gian vườn mát.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'azalea'),
    ('rhododendron', 33, 'Rhododendron', 'Đỗ quyên lớn', 'A large shrub bloom with rounded trusses of flowers.', 'Đỗ quyên lớn nở thành chùm tròn dày trên cây bụi xanh.', 'A mountain and woodland shrub with showy flower clusters.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Các cụm hoa lớn tạo điểm nhấn mạnh trong vườn rừng và vùng núi.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'rhododendron'),
    ('wisteria', 34, 'Wisteria', 'Tử đằng', 'A climbing vine with hanging chains of purple flowers.', 'Tử đằng là dây leo gỗ với những chùm hoa tím rủ dài.', 'A woody vine famous for cascading spring racemes.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Khi nở rộ, các chuỗi hoa tạo thành màn thác mềm trên giàn.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'wisteria'),
    ('bougainvillea', 35, 'Bougainvillea', 'Hoa giấy', 'A vivid climbing plant whose color comes from papery bracts.', 'Hoa giấy nổi bật nhờ các lá bắc mỏng như giấy và màu rất chói.', 'A warm-climate vine known for papery, bright bracts.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Cây leo này hợp khí hậu ấm, thường phủ tường và cổng bằng sắc hồng tím.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'bougainvillea'),
    ('morningGlory', 36, 'Morning Glory', 'Bìm bìm', 'A twining vine with trumpet flowers that often open early.', 'Bìm bìm là dây leo có hoa kèn thường mở vào buổi sáng.', 'A climbing flower known for morning-opening trumpets.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Hoa leo nhanh, tạo cảm giác tươi mới ở hàng rào và giàn nhỏ.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'morning-glory'),
    ('sweetPea', 37, 'Sweet Pea', 'Đậu thơm', 'A scented climbing flower with soft, fluttery petals.', 'Đậu thơm có cánh mềm như cánh bướm và hương dịu ngọt.', 'A fragrant annual vine often grown for bouquets.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Dây leo hằng năm này thường được trồng để cắt cành thơm.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'sweet-pea'),
    ('pansy', 38, 'Pansy', 'Hoa păng-xê', 'A small cool-season flower with face-like markings.', 'Hoa păng-xê nhỏ xinh với các mảng màu giống khuôn mặt.', 'A compact bloom loved for expressive markings.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Loài hoa mùa mát này được yêu thích vì biểu cảm vui và nhiều phối màu.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'pansy'),
    ('violet', 39, 'Violet', 'Hoa tím', 'A small flower with heart-shaped leaves and soft color.', 'Hoa tím nhỏ, lá hình tim và sắc màu dịu trong nơi râm mát.', 'A modest bloom often found in cool, shady places.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Dáng hoa khiêm nhường khiến violet thường gắn với sự tinh tế.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'violet'),
    ('primrose', 40, 'Primrose', 'Anh thảo', 'An early-season flower that brings color after winter.', 'Anh thảo nở sớm, mang màu sắc trở lại sau mùa đông.', 'A low-growing flower often associated with early spring.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Cây thấp, hợp viền lối đi và các góc vườn mùa xuân.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'primrose'),
    ('cosmos', 41, 'Cosmos', 'Sao nhái', 'A light, airy annual with daisy-like flowers.', 'Sao nhái có hoa như cúc, thân mảnh và tán lá mềm như lông.', 'A summer annual valued for feathery foliage and open blooms.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Hoa đung đưa nhẹ trong gió, tạo cảm giác thoáng đãng cho vườn hè.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'cosmos'),
    ('aster', 42, 'Aster', 'Cúc sao', 'A starry late-season flower loved by pollinators.', 'Cúc sao có bông nhỏ hình sao, thường nở muộn trong mùa.', 'A daisy-like bloom that often appears late in the season.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Hoa là nguồn mật quý cho côn trùng thụ phấn khi cuối mùa ít hoa hơn.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'aster'),
    ('calendula', 43, 'Calendula', 'Cúc kim tiền', 'A golden flower also known as pot marigold.', 'Cúc kim tiền có sắc vàng cam ấm và còn gọi là pot marigold.', 'A bright edible flower historically used in herbal preparations.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Cánh hoa từng được dùng trong các cách chế biến và thảo mộc truyền thống.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'calendula'),
    ('gerbera', 44, 'Gerbera', 'Đồng tiền', 'A bold daisy-like flower with clean, saturated colors.', 'Đồng tiền có mặt hoa lớn, màu sạch và rất nổi bật trong bó hoa.', 'A popular cut flower with large, simple faces.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Dáng cúc đơn giản giúp màu sắc của gerbera trông tươi và hiện đại.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'gerbera'),
    ('lily', 45, 'Lily', 'Hoa ly', 'A large elegant bloom with strong petals and often rich fragrance.', 'Hoa ly có bông lớn, cánh mạnh và nhiều giống có hương thơm đậm.', 'A bulb flower known for dramatic trumpet or star forms.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Các dạng hoa có thể giống kèn, ngôi sao hoặc cánh mở rộng.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'lily'),
    ('callaLily', 46, 'Calla Lily', 'Hoa rum', 'A smooth sculptural flower shaped like a rolled cup.', 'Hoa rum có dáng cúp trơn mượt, ôm quanh phần trụ ở giữa.', 'A graceful bloom with a single spathe around a central spike.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Một lá bắc lớn tạo nên hình dáng thanh lịch của bông hoa.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'calla-lily'),
    ('lilyOfTheValley', 47, 'Lily of the Valley', 'Linh lan', 'A tiny bell flower with a sweet fragrance.', 'Linh lan có chuỗi chuông trắng nhỏ và hương ngọt tinh tế.', 'A woodland flower known for small white bells.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Loài hoa rừng này thường gợi cảm giác trong trẻo và cổ điển.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'lily-of-the-valley'),
    ('amaryllis', 48, 'Amaryllis', 'Lan huệ', 'A large bulb flower often grown indoors for winter color.', 'Lan huệ có thân cao và hoa kèn lớn, thường nở rực trong nhà.', 'A bulb bloom with tall stems and dramatic trumpets.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Củ amaryllis được trồng nhiều để có màu sắc vào mùa lạnh.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'amaryllis'),
    ('clematis', 49, 'Clematis', 'Ông lão', 'A climbing flower with starry blossoms on vines.', 'Ông lão là dây leo có hoa hình sao bám trên giàn hoặc hàng rào.', 'A flowering vine grown on trellises and fences.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Hoa giúp làm mềm các khung leo bằng mảng màu rộng và thanh.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'clematis'),
    ('honeysuckle', 50, 'Honeysuckle', 'Kim ngân', 'A fragrant tubular flower that grows on shrubs or vines.', 'Kim ngân có hoa ống thơm, mọc trên bụi hoặc dây leo.', 'A nectar-rich bloom often visited by pollinators.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Hoa giàu mật nên thường thu hút ong, bướm và chim nhỏ.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'honeysuckle'),
    ('fuchsia', 51, 'Fuchsia', 'Lồng đèn', 'A dangling flower shaped like a tiny lantern.', 'Lồng đèn có hoa rủ xuống như chiếc đèn nhỏ nhiều màu.', 'A hanging bloom with contrasting sepals and petals.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Cánh đài và cánh hoa tương phản làm bông hoa trông rất sinh động.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'fuchsia'),
    ('plumeria', 52, 'Plumeria', 'Đại sứ', 'A tropical flower with waxy petals and sweet fragrance.', 'Đại sứ có cánh dày, mùi ngọt và vẻ nhiệt đới mềm mại.', 'A warm-climate bloom often used in leis.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Hoa thường được dùng làm vòng hoa ở nhiều vùng khí hậu ấm.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'plumeria'),
    ('birdOfParadise', 53, 'Bird of Paradise', 'Thiên điểu', 'A dramatic tropical flower shaped like a bird in flight.', 'Thiên điểu có dáng như chú chim đang bay với sắc cam xanh mạnh.', 'A sculptural bloom with bold orange and blue forms.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Cấu trúc hoa điêu khắc khiến nó trở thành điểm nhấn rất dễ nhận ra.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'bird-of-paradise'),
    ('protea', 54, 'Protea', 'Hoa protea', 'A bold architectural flower with a prehistoric feel.', 'Hoa protea có dáng kiến trúc mạnh và vẻ cổ xưa độc đáo.', 'A South African bloom known for sturdy bracts.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Các lá bắc cứng tạo hình bông hoa bền và nổi bật.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'protea'),
    ('banksia', 55, 'Banksia', 'Hoa banksia', 'A cylindrical flower spike with a wild sculptural texture.', 'Hoa banksia có trụ hoa dày với bề mặt hoang dã, nhiều kết cấu.', 'An Australian bloom made of many tiny flowers.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Mỗi trụ gồm rất nhiều hoa nhỏ, tạo thành dáng điêu khắc đặc biệt.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'banksia'),
    ('waratah', 56, 'Waratah', 'Hoa waratah', 'A striking red flower head native to Australia.', 'Hoa waratah là đầu hoa đỏ rực, tròn chắc và rất ấn tượng.', 'A bold inflorescence with a strong rounded form.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Cụm hoa lớn tạo cảm giác mạnh mẽ như một biểu tượng trong vườn.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'waratah'),
    ('edelweiss', 57, 'Edelweiss', 'Nhung tuyết', 'A pale alpine flower with woolly star-shaped bracts.', 'Nhung tuyết có lá bắc trắng như sao, phủ lông mềm để chịu núi cao.', 'An alpine bloom adapted to high mountain conditions.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Loài hoa alpine này thích nghi với nắng gắt và khí hậu lạnh trên cao.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'edelweiss'),
    ('yarrow', 58, 'Yarrow', 'Cỏ thi', 'A flat-topped cluster flower often found in meadows.', 'Cỏ thi nở thành tán phẳng gồm rất nhiều hoa nhỏ li ti.', 'A hardy meadow plant with many tiny clustered blooms.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Cây bền khỏe, thường xuất hiện ở đồng cỏ và những khu vườn tự nhiên.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'yarrow'),
    ('cornflower', 59, 'Cornflower', 'Thanh cúc', 'A vivid blue wildflower with fringed petals.', 'Thanh cúc có màu xanh trong và cánh viền tua rất đặc trưng.', 'A field flower famous for clear blue color.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Sắc xanh đồng nội khiến hoa dễ nổi bật giữa các loài cúc khác.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'cornflower'),
    ('forgetMeNot', 60, 'Forget-me-not', 'Lưu ly', 'A tiny blue flower with a sentimental name.', 'Lưu ly là hoa xanh rất nhỏ với tâm vàng, tên gợi sự nhớ thương.', 'A small bloom often linked with remembrance.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Những bông hoa bé thường mọc thành cụm mềm ở nơi mát ẩm.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'forget-me-not'),
    ('babyBreath', 61, 'Baby’s Breath', 'Hoa bi', 'A cloud of tiny white flowers often used in bouquets.', 'Hoa bi tạo thành làn mây trắng li ti trong các bó hoa.', 'A filler flower that creates airy texture.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Các cành mảnh giúp bó hoa có cảm giác nhẹ và thoáng.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'baby-breath'),
    ('bleedingHeart', 62, 'Bleeding Heart', 'Trái tim rỉ máu', 'A heart-shaped dangling bloom on arching stems.', 'Trái tim rỉ máu có hoa hình tim rủ trên cành cong mềm.', 'A shade garden flower with distinctive heart forms.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Dáng hoa rất riêng khiến cây nổi bật trong các góc vườn râm.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'bleeding-heart'),
    ('hollyhock', 63, 'Hollyhock', 'Mãn đình hồng', 'A tall cottage-garden flower with stacked blooms.', 'Mãn đình hồng mọc cao với nhiều hoa xếp dọc thân thẳng.', 'A vertical garden flower often grown against walls.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Hoa thường được trồng sát tường để tạo chiều cao cho vườn cottage.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'hollyhock'),
    ('delphinium', 64, 'Delphinium', 'Phi yến', 'A tall spike of blue, purple, or white flowers.', 'Phi yến có tháp hoa cao màu xanh, tím hoặc trắng rất nổi.', 'A dramatic flower spike that adds height to borders.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Dáng hoa dựng đứng giúp luống hoa có chiều sâu và chiều cao.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'delphinium'),
    ('lupine', 65, 'Lupine', 'Hoa lupin', 'A spire of pea-like flowers with bold garden color.', 'Hoa lupin tạo thành búp tháp gồm nhiều hoa họ đậu nhỏ.', 'A flower spike from the pea family with palmate leaves.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Lá xòe như bàn tay là một dấu hiệu dễ nhận ra của lupin.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'lupine'),
    ('phlox', 66, 'Phlox', 'Hoa phlox', 'A clustered flower that can carpet ground or fill borders.', 'Hoa phlox nở thành cụm sao nhỏ, có thể phủ nền hoặc lấp đầy luống.', 'A bloom known for masses of small starry flowers.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Khi nở dày, phlox tạo những mảng màu mềm và thơm nhẹ.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'phlox'),
    ('verbena', 67, 'Verbena', 'Mã tiên thảo', 'A small clustered flower that blooms over a long season.', 'Mã tiên thảo có cụm hoa nhỏ và mùa nở kéo dài.', 'A nectar-friendly plant often used in borders and baskets.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Hoa nhiều mật nên thường được trồng để thu hút bướm.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'verbena'),
    ('salvia', 68, 'Salvia', 'Xô thơm hoa', 'A spike flower loved by bees and hummingbirds.', 'Xô thơm hoa nở thành bông ống dựng đứng, rất hợp với ong.', 'A garden flower with aromatic leaves and tubular blooms.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Lá thơm và dáng hoa cao giúp salvia dễ nhận ra trong vườn nắng.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'salvia'),
    ('beeBalm', 69, 'Bee Balm', 'Bạc hà ong', 'A shaggy flower head that attracts pollinators.', 'Bạc hà ong có đầu hoa tua xù như pháo hoa nhỏ.', 'A mint-family bloom with aromatic foliage.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Thuộc họ bạc hà, cây có lá thơm và rất hấp dẫn các loài thụ phấn.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'bee-balm'),
    ('echinacea', 70, 'Echinacea', 'Cúc tím', 'A cone-centered daisy often grown in sunny beds.', 'Cúc tím có cánh rủ quanh nón nhụy nổi ở giữa.', 'A prairie flower known for a raised central cone.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Loài hoa thảo nguyên này chịu nắng tốt và có dáng trung tâm rất rõ.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'echinacea'),
    ('blackEyedSusan', 71, 'Black-eyed Susan', 'Cúc mắt đen', 'A golden daisy with a dark central cone.', 'Cúc mắt đen có cánh vàng tươi quanh tâm nâu sẫm.', 'A sunny prairie-style flower with a dark eye.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Dáng hoa đồng cỏ rực rỡ giúp luống hoa trông ấm và vui.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'black-eyed-susan'),
    ('hellebore', 72, 'Hellebore', 'Hoa hồng Giáng sinh', 'A winter or early-spring flower with nodding blooms.', 'Hoa hồng Giáng sinh nở cúi đầu vào mùa lạnh hoặc đầu xuân.', 'A shade-tolerant perennial that blooms in cool seasons.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Cây chịu bóng tốt, mang hoa khi nhiều loài khác còn ngủ đông.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'hellebore'),
    ('cyclamen', 73, 'Cyclamen', 'Anh thảo tiên', 'A swept-back petal flower with patterned leaves.', 'Anh thảo tiên có cánh bật ngược như cánh bướm và lá vân đẹp.', 'A cool-season flower with reflexed petals.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Hoa ưa mùa mát, nổi bật nhờ dáng cánh xoay ngược rất riêng.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'cyclamen'),
    ('crocus', 74, 'Crocus', 'Nghệ tây cảnh', 'A small cup flower that often appears very early.', 'Nghệ tây cảnh là hoa cúp nhỏ thường xuất hiện rất sớm.', 'An early bulb-like bloom that can push through cold soil.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Những bông crocus có thể nhú qua đất lạnh để báo mùa mới.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'crocus'),
    ('snowdrop', 75, 'Snowdrop', 'Hoa giọt tuyết', 'A tiny white nodding flower that signals late winter.', 'Hoa giọt tuyết có chuông trắng nhỏ rủ xuống trên thân mảnh.', 'A cold-season bulb with delicate white bells.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Đây là một trong những tín hiệu dịu dàng của cuối đông.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'snowdrop'),
    ('allium', 76, 'Allium', 'Hoa hành', 'A spherical flower head made from many tiny star blooms.', 'Hoa hành có đầu hoa tròn như quả cầu gồm nhiều sao nhỏ.', 'An ornamental onion with globe-shaped flower heads.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Dáng cầu tím trên thân cao làm allium rất nổi trong luống hoa.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'allium'),
    ('gladiolus', 77, 'Gladiolus', 'Lay ơn', 'A tall sword-leaved flower spike popular in arrangements.', 'Lay ơn có lá như kiếm và hoa xếp dọc trên một cành cao.', 'A corm flower with blossoms stacked along a stem.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Củ giả của cây cho những cành hoa dài được chuộng trong cắm hoa.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'gladiolus'),
    ('canna', 78, 'Canna', 'Hoa dong riềng', 'A tropical-looking flower with broad leaves.', 'Hoa dong riềng có lá bản lớn và bông nhiệt đới màu mạnh.', 'A warm-season plant known for bold foliage and blooms.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Cây mang cảm giác xanh rậm, ấm áp nhờ lá rộng và hoa nổi.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'canna'),
    ('nasturtium', 79, 'Nasturtium', 'Sen cạn', 'A bright edible flower with round leaves.', 'Sen cạn có lá tròn như khiên và hoa vàng cam ăn được.', 'A trailing flower often grown in containers and beds.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Thân bò hoặc rủ giúp cây hợp với chậu, bồn và viền luống.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'nasturtium'),
    ('petunia', 80, 'Petunia', 'Dạ yến thảo', 'A trumpet-shaped flower common in baskets and containers.', 'Dạ yến thảo có hoa kèn mềm, nhiều màu và thường nở rất lâu.', 'A long-blooming annual with many colors and patterns.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Cây phổ biến trong giỏ treo vì phủ hoa dày qua mùa ấm.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'petunia'),
    ('impatiens', 81, 'Impatiens', 'Mai địa thảo', 'A shade-friendly flower with soft rounded petals.', 'Mai địa thảo có cánh tròn mềm, rất hợp những góc vườn râm.', 'A popular bedding plant for shady color.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Đây là cây bedding quen thuộc để thêm màu ở nơi ít nắng.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'impatiens'),
    ('lantana', 82, 'Lantana', 'Ngũ sắc', 'A clustered flower whose colors can shift as blooms age.', 'Ngũ sắc nở thành cụm hoa nhỏ, màu có thể đổi khi hoa già.', 'A warm-climate flower cluster loved by butterflies.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Các cụm hoa ấm màu thường thu hút bướm trong khí hậu nắng.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'lantana'),
    ('nicotiana', 83, 'Nicotiana', 'Thuốc lá cảnh', 'A starry tubular flower often fragrant in the evening.', 'Thuốc lá cảnh có hoa ống hình sao, nhiều giống thơm về chiều.', 'An ornamental tobacco flower with long tubes.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Ống hoa dài và dáng mảnh tạo cảm giác nhẹ trong vườn tối.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'nicotiana'),
    ('stock', 84, 'Stock', 'Hoa mõm chó thơm', 'A fragrant spike flower used in cool-season bouquets.', 'Hoa mõm chó thơm có tháp hoa dày và mùi hương giống đinh hương.', 'A cut flower valued for clove-like scent.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Hoa cắt cành mùa mát này được yêu vì mùi thơm và màu dịu.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'stock'),
    ('scabiosa', 85, 'Scabiosa', 'Hoa pincushion', 'A pincushion-shaped bloom with delicate texture.', 'Hoa pincushion có tâm như đệm ghim và viền cánh mềm.', 'A flower named for its pin-like central details.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Các chi tiết nhỏ ở tâm hoa làm scabiosa có kết cấu rất duyên.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'scabiosa'),
    ('nigella', 86, 'Nigella', 'Tình yêu trong sương', 'A delicate flower surrounded by fine, misty foliage.', 'Tình yêu trong sương có hoa xanh nhạt nằm giữa tán lá mảnh như sương.', 'A bloom often called love-in-a-mist.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Sau khi nở, cây còn tạo quả hạt phồng trang trí rất lạ.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'nigella'),
    ('borage', 87, 'Borage', 'Lưu ly sao', 'A star-shaped blue flower with edible blossoms.', 'Lưu ly sao có hoa xanh hình sao rủ nhẹ trên thân lá có lông.', 'A herb flower that attracts bees.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Hoa ăn được và là nguồn mật hấp dẫn cho ong.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'borage'),
    ('chamomile', 88, 'Chamomile', 'Cúc La Mã', 'A small daisy-like flower known for gentle herbal tea.', 'Cúc La Mã có hoa nhỏ như cúc trắng và tâm vàng dịu.', 'An aromatic bloom often dried for infusions.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Hoa thơm thường được phơi khô để pha trà thảo mộc nhẹ.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'chamomile'),
    ('clover', 89, 'Clover', 'Hoa cỏ ba lá', 'A small rounded flower head common in meadows.', 'Hoa cỏ ba lá có đầu hoa tròn nhỏ và lá chét ba phiến.', 'A legume flower often visited by bees.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Là cây họ đậu, clover thường được ong ghé thăm để lấy mật.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'clover'),
    ('heather', 90, 'Heather', 'Thạch thảo bụi', 'A tiny bell-like flower on low woody shrubs.', 'Thạch thảo bụi có vô số chuông nhỏ trên cành gỗ thấp.', 'A moorland plant known for masses of small blooms.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Khi nở đồng loạt, heather tạo mảng màu mềm trên vùng đồi hoang.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'heather'),
    ('gorse', 91, 'Gorse', 'Kim tước gai', 'A bright yellow shrub flower with coconut-like scent.', 'Kim tước gai là cây bụi có hoa vàng sáng và cành gai xanh.', 'A spiny shrub with pea-family flowers.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Hoa họ đậu của gorse đôi khi có hương gợi nhớ mùi dừa.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'gorse'),
    ('broom', 92, 'Broom', 'Kim tước', 'A yellow pea-like flower on arching shrub stems.', 'Kim tước có hoa vàng hình hạt đậu trên những cành xanh cong.', 'A shrub flower that brightens dry sunny places.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Cây làm sáng các nơi khô nắng bằng sắc vàng nhẹ và dáng thanh.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'broom'),
    ('queenAnnesLace', 93, 'Queen Anne’s Lace', 'Hoa ren Nữ hoàng Anne', 'A lacy white umbel made of many tiny flowers.', 'Hoa ren Nữ hoàng Anne có tán trắng mỏng như ren từ rất nhiều hoa nhỏ.', 'A wildflower with umbrella-like flower clusters.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Cụm hoa dạng ô thường có một chấm sẫm nhỏ ở giữa.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'queen-annes-lace'),
    ('tansy', 94, 'Tansy', 'Cúc ngải', 'A button-like yellow flower in flat clusters.', 'Cúc ngải có các nút hoa vàng tròn, gần như không có cánh tia.', 'A hardy herbaceous plant with small golden discs.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Lá xẻ sâu và cụm hoa phẳng giúp tansy trông rất rõ dáng.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'tansy'),
    ('goldenrod', 95, 'Goldenrod', 'Cúc vàng hoang', 'A plume of tiny yellow flowers in late-season meadows.', 'Cúc vàng hoang có chùm hoa vàng li ti thành plume cuối mùa.', 'A pollinator-friendly flower often blooming late.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Hoa là nguồn mật muộn quan trọng cho nhiều loài thụ phấn.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'goldenrod'),
    ('milkweed', 96, 'Milkweed', 'Bông tai', 'A cluster flower important to monarch butterflies.', 'Bông tai có cụm hoa hồng tím nhỏ và lá bản rộng đối nhau.', 'A plant valued as host habitat for monarch caterpillars.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Cây là nguồn sống quan trọng cho sâu bướm vua.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'milkweed'),
    ('passionflower', 97, 'Passionflower', 'Lạc tiên', 'An intricate vine flower with a crown of filaments.', 'Lạc tiên có hoa cực kỳ phức tạp với vòng tua tím trắng ở giữa.', 'A complex bloom that looks almost architectural.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Dáng hoa như một công trình nhỏ, rất dễ nhận ra trên dây leo.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'passionflower'),
    ('hoya', 98, 'Hoya', 'Cẩm cù', 'A waxy star-shaped flower in rounded clusters.', 'Cẩm cù có cụm hoa sáp hình sao, trông như làm bằng sứ.', 'A houseplant bloom known for porcelain-like flowers.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Lá dày bóng và hoa có tâm đỏ nhỏ khiến hoya rất nổi trong nhà.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'hoya'),
    ('stephanotis', 99, 'Stephanotis', 'Nhài Madagascar', 'A waxy white fragrant flower used in wedding bouquets.', 'Nhài Madagascar có hoa trắng sáp, thơm và mọc trên dây leo.', 'A vine flower prized for clean white scent.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Hoa thường xuất hiện trong bó cưới nhờ vẻ sạch và hương dịu.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'stephanotis'),
    ('tuberose', 100, 'Tuberose', 'Huệ thơm', 'A white flower spike famous for intense perfume.', 'Huệ thơm có cành hoa trắng dạng ống và mùi hương rất đậm.', 'A night-fragrant bloom used in perfumery.', 'Its varieties can differ widely in color, size, scent, or blooming season.', 'In FlowerDoro, this bloom adds another collectible shape to the garden.', 'Hoa thơm về đêm và được dùng nhiều trong ngành hương liệu.', 'Các giống khác nhau có thể khác về màu sắc, kích thước, hương thơm hoặc mùa nở.', 'Trong FlowerDoro, bông hoa này thêm một dáng sưu tầm mới cho khu vườn.', 'common', 'tuberose')
ON CONFLICT (kind) DO UPDATE SET
    sort_order = EXCLUDED.sort_order,
    english_name = EXCLUDED.english_name,
    vietnamese_name = EXCLUDED.vietnamese_name,
    english_description = EXCLUDED.english_description,
    vietnamese_description = EXCLUDED.vietnamese_description,
    english_fact_1 = EXCLUDED.english_fact_1,
    english_fact_2 = EXCLUDED.english_fact_2,
    english_fact_3 = EXCLUDED.english_fact_3,
    vietnamese_fact_1 = EXCLUDED.vietnamese_fact_1,
    vietnamese_fact_2 = EXCLUDED.vietnamese_fact_2,
    vietnamese_fact_3 = EXCLUDED.vietnamese_fact_3,
    rarity = EXCLUDED.rarity,
    asset_name = EXCLUDED.asset_name,
    updated_at = now();
